server {
	listen 5050 default_server;
	listen [::]:5050 default_server;

	root /var/www/html/wordpress;
	index index.php index.html index.htm;
	
	server_name	wordpress;

	location ~ \.php$ {
		fastcgi_pass	127.0.0.1:9000;
		fastcgi_index	index.php;
		include			fastcgi.conf;
	}
}
