server {
	listen 5000 default_server;
	listen [::]:5000 default_server;

	root /var/www/html/phpmyadmin;
	index index.php index.html index.htm;
	
	server_name	phpmyadmin;

	location ~ \.php$ {
		fastcgi_pass	127.0.0.1:9000;
		fastcgi_index	index.php;
		include			fastcgi.conf;
	}
}
