server {
	listen 80 default_server;
	listen [::]:80 default_server;

	server_name _;
#	# http to https : redirect
	return 301 https://$host$request_uri;
}


server {
	listen 443 ssl;
	listen [::]:443 ssl;

	server_name _;
	root /var/www/html;
	index index.html index.htm index.php;

	charset utf-8;

	ssl on;
	ssl_certificate /etc/ssl/certs/localhost.dev.crt;
	ssl_certificate_key /etc/ssl/private/localhost.dev.key;

	location = /wordpress {
		return 307 http://MINIKUBE_IP:5050;
	}
	location ~ ^/wordpress/(.*)$ {
		return 307 http://MINIKUBE_IP:5050/$1$is_args$args;
	}

	location /phpmyadmin/ {
		proxy_set_header X-Forwarded-By $server_addr:$server_port;
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header Host $host;
		proxy_pass http://MINIKUBE_IP:5000/;
	}
	location ~* ^/index.php(.*)$ {
		return 307 https://MINIKUBE_IP/phpmyadmin/index.php$1$is_args$args;
	}

	location / {
		try_files $uri $uri/ =404;
	}
}
